[manifest] # Header for the file, this should only be here once at the beginning
version = "0.0.1"
priority = 0 # Priority for loading the file


[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
        func = (function()
                play_sound('glass'..math.random(1, 6), math.random()*0.2 + 0.9,0.5)
                play_sound('generic1', math.random()*0.2 + 0.9,0.5)
            return true end)'''
position = "at"
payload = '''
        func = (function()
                if self.config.center.key == 'm_glass' then
                    play_sound('glass'..math.random(1, 6), math.random()*0.2 + 0.9,0.5)
                    play_sound('generic1', math.random()*0.2 + 0.9,0.5)
                end
            return true end)'''
match_indent = false